# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela_saida.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_saida(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        MainWindow.setStyleSheet("background-color: rgb(106, 106, 106);\n" "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.line_qtd = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.line_qtd.setFont(font)
        self.line_qtd.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "border-radius:10px;"
        )
        self.line_qtd.setText("")
        self.line_qtd.setMaxLength(30)
        self.line_qtd.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_qtd.setAlignment(QtCore.Qt.AlignCenter)
        self.line_qtd.setObjectName("line_qtd")
        self.gridLayout.addWidget(self.line_qtd, 1, 2, 1, 1)
        self.line_codprod = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.line_codprod.setFont(font)
        self.line_codprod.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "border-radius:10px;"
        )
        self.line_codprod.setText("")
        self.line_codprod.setMaxLength(30)
        self.line_codprod.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_codprod.setAlignment(QtCore.Qt.AlignCenter)
        self.line_codprod.setObjectName("line_codprod")
        self.gridLayout.addWidget(self.line_codprod, 0, 1, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem1)
        self.msg_box = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.msg_box.setFont(font)
        self.msg_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.msg_box.setStyleSheet("color: rgb(85, 255, 0);")
        self.msg_box.setText("")
        self.msg_box.setAlignment(QtCore.Qt.AlignCenter)
        self.msg_box.setObjectName("msg_box")
        self.verticalLayout_2.addWidget(self.msg_box)
        self.btn_gerar_saida = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_gerar_saida.setFont(font)
        self.btn_gerar_saida.setStyleSheet(
            "QPushButton{\n"
            "text-decoration: none;\n"
            "border: none;\n"
            "padding: 12px 40px;\n"
            "font-size: 16px;\n"
            "background-color: gray;\n"
            "color: #fff;\n"
            "border-radius: 5px;\n"
            "box-shadow: 7px 6px 28px 1px rgba(0, 0, 0, 0.24);\n"
            "cursor: pointer;\n"
            "outline: none;\n"
            "transition: 0.2s all;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "text-decoration: none;\n"
            "border: none;\n"
            "padding: 12px 40px;\n"
            "font-size: 16px;\n"
            "background-color: rgb(99, 99, 99);\n"
            "color: #fff;\n"
            "border-radius: 5px;\n"
            "box-shadow: 7px 6px 28px 1px rgba(0, 0, 0, 0.24);\n"
            "cursor: pointer;\n"
            "outline: none;\n"
            "transition: 0.2s all;\n"
            "}\n"
            ""
        )
        self.btn_gerar_saida.setObjectName("btn_gerar_saida")
        self.verticalLayout_2.addWidget(self.btn_gerar_saida)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Gerar Saida"))
        self.label_6.setText(_translate("MainWindow", "Quantidade"))
        self.label_8.setText(_translate("MainWindow", "Cod. Produto"))
        self.btn_gerar_saida.setText(_translate("MainWindow", "Gerar"))
