# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 540)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(350, 540))
        MainWindow.setMaximumSize(QtCore.QSize(350, 540))
        MainWindow.setStyleSheet("background-color: rgb(106, 106, 106);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 190, 231, 31))
        self.lineEdit.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "border-radius:10px;"
        )
        self.lineEdit.setMaxLength(2000)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 290, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "border-radius:10px;"
        )
        self.lineEdit_2.setMaxLength(15)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 140, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 240, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 360, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(
            "QPushButton{\n"
            "text-decoration: none;\n"
            "border: none;\n"
            "padding: 12px 40px;\n"
            "font-size: 16px;\n"
            "background-color: gray;\n"
            "color: #fff;\n"
            "border-radius: 5px;\n"
            "box-shadow: 7px 6px 28px 1px rgba(0, 0, 0, 0.24);\n"
            "cursor: pointer;\n"
            "outline: none;\n"
            "transition: 0.2s all;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "text-decoration: none;\n"
            "border: none;\n"
            "padding: 12px 40px;\n"
            "font-size: 16px;\n"
            "background-color: rgb(99, 99, 99);\n"
            "color: #fff;\n"
            "border-radius: 5px;\n"
            "box-shadow: 7px 6px 28px 1px rgba(0, 0, 0, 0.24);\n"
            "cursor: pointer;\n"
            "outline: none;\n"
            "transition: 0.2s all;\n"
            "}\n"
            ""
        )
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 321, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 320, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 420, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(
            "QPushButton{\n"
            "text-decoration: none;\n"
            "border: none;\n"
            "padding: 12px 40px;\n"
            "font-size: 16px;\n"
            "background-color: gray;\n"
            "color: #fff;\n"
            "border-radius: 5px;\n"
            "box-shadow: 7px 6px 28px 1px rgba(0, 0, 0, 0.24);\n"
            "cursor: pointer;\n"
            "outline: none;\n"
            "transition: 0.2s all;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "text-decoration: none;\n"
            "border: none;\n"
            "padding: 12px 40px;\n"
            "font-size: 16px;\n"
            "background-color: rgb(99, 99, 99);\n"
            "color: #fff;\n"
            "border-radius: 5px;\n"
            "box-shadow: 7px 6px 28px 1px rgba(0, 0, 0, 0.24);\n"
            "cursor: pointer;\n"
            "outline: none;\n"
            "transition: 0.2s all;\n"
            "}\n"
            ""
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 500, 121, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Usuario"))
        self.label_2.setText(_translate("MainWindow", "Senha"))
        self.pushButton.setText(_translate("MainWindow", "Entrar"))
        self.label_3.setText(_translate("MainWindow", "Sistema de Gerenciamento"))
        self.pushButton_2.setText(_translate("MainWindow", "Cadastrar"))
        self.label_5.setText(_translate("MainWindow", "By: Ryan"))
